---
title: "資料讀取與匯出 課堂練習"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

####有一個網路上的csv檔，下載網址為https://goo.gl/RdngMn ，請問如何以撰寫程式碼的方式匯入R中作分析? <br/>
####匯入後，此表格有幾個欄位?
#### 解答

```{r q1}
library(readr)
data_csv<-read_csv("https://goo.gl/RdngMn")
length(data_csv)  ##欄位數寫法1
dim(data_csv)[2]  ##欄位數寫法2
ncol(data_csv)    ##欄位數寫法3
```
<hr/>

####下列哪幾種檔案可以匯入R作分析?
#### 解答
Excel檔、MySQL資料庫檔、純文字檔 (.txt)、圖片檔

<hr/>


####Open Data常用的資料格式有哪幾個?
#### 解答
csv檔、JSON檔、XML檔

<hr/>

####嘗試在政府資料開放平臺中，找到紫外線即時監測資料，並嘗試將XML檔案讀到R中，取出所有測站的名稱與紫外線強度資料。
Windows電腦有編碼問題，若讀出資料是亂碼，請將資料轉成BIG5<br/>
方法如下:iconv(文字向量,from="UTF8",to="big5")

- xmlParse(xml檔案路徑)
- xpathSApply(資料集,要選取的資料XML的tag名稱,xmlValue)

#### 解答
```{r q2}
# 資料下載網址：http://opendata2.epa.gov.tw/UV/UV.xml　（紫外線即時監測資料）
library(XML)
UV <- xmlParse("http://opendata2.epa.gov.tw/UV/UV.xml")
SiteName<-xpathSApply(UV,"//SiteName",xmlValue)
#iconv(SiteName,from="UTF8",to="big5")  #如果資料出現亂碼再跑這行
SiteName
UVI<-xpathSApply(UV,"//UVI",xmlValue)
#iconv(UVI,from="UTF8",to="big5")  #如果資料出現亂碼再跑這行
UVI
##將資料整理成資料框寫法
UV_dataset<-data.frame(SiteName=xpathSApply(UV,"//SiteName",xmlValue),
            UVI=xpathSApply(UV,"//UVI",xmlValue))
UV_dataset
```
<hr/>
